In [317]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import regex as re

pd.options.display.max_columns = 50

In [318]:
df_match = pd.read_csv('FIFA WC data/WorldCupMatches.csv')
df_players = pd.read_csv('FIFA WC data/WorldCupPlayers.csv')
df_cups = pd.read_csv('FIFA WC data/WorldCups.csv')

In [319]:
df_match

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [320]:
df_match.isna().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [321]:
df_match.dropna(how='all', inplace=True)
df_match.drop_duplicates(inplace=True)

In [322]:
df_match['Datetime'] = pd.to_datetime(df_match['Datetime'], format='mixed')

In [323]:
df_match.isna().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              1
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [324]:
df_match[df_match['Attendance'].isna()]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
823,2014.0,2014-06-30 17:00:00,Round of 16,Estadio Beira-Rio,Porto Alegre,Germany,2.0,1.0,Algeria,Germany win after extra time,NaN,0.0,0.0,RICCI Sandro (BRA),DE CARVALHO Emerson (BRA),VAN GASSE Marcelo (BRA),255951.0,300186460.0,GER,ALG

In [325]:
df_match[df_match['Stadium'] == 'Estadio Beira-Rio']

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
781,2014.0,2014-06-15 16:00:00,Group E,Estadio Beira-Rio,Porto Alegre,France,3.0,0.0,Honduras,,43012.0,1.0,0.0,RICCI Sandro (BRA),DE CARVALHO Emerson (BRA),VAN GASSE Marcelo (BRA),255931.0,300186496.0,FRA,HON
789,2014.0,2014-06-18 13:00:00,Group B,Estadio Beira-Rio,Porto Alegre,Australia,2.0,3.0,Netherlands,,42877.0,1.0,1.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255931.0,300186478.0,AUS,NED
802,2014.0,2014-06-22 16:00:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea Republic,2.0,4.0,Algeria,,42732.0,0.0,3.0,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931.0,300186495.0,KOR,ALG
812,2014.0,2014-06-25 13:00:00,Group F,Estadio Beira-Rio,Porto Alegre,Nigeria,2.0,3.0,Argentina,,43285.0,1.0,2.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255931.0,300186458.0,NGA,ARG
823,2014.0,2014-06-30 17:00:00,Round of 16,Estadio Beira-Rio,Porto Alegre,Germany,2.0,1.0,Algeria,Germany win after extra time,NaN,0.0,0.0,RICCI Sandro (BRA),DE CARVALHO Emerson (BRA),VAN GASSE Marcelo (BRA),255951.0,300186460.0,GER,ALG

In [326]:
df_match['Attendance'].fillna(df_match[df_match['Stadium'] == 'Estadio Beira-Rio']['Attendance'].mean(), inplace=True)

In [327]:
df_match.isna().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [328]:
float_columns = ['Year', 'Home Team Goals', 'Away Team Goals', 'Half-time Home Goals', 'Half-time Away Goals', 'RoundID', 'MatchID', 'Attendance']
df_match[float_columns] = df_match[float_columns].astype(int)

In [329]:
df_match.info()

<class 'pandas.core.frame.DataFrame'>
Index: 836 entries, 0 to 835
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  836 non-null    int32
 1   Datetime              836 non-null    datetime64[ns]
 2   Stage                 836 non-null    object
 3   Stadium               836 non-null    object
 4   City                  836 non-null    object
 5   Home Team Name        836 non-null    object
 6   Home Team Goals       836 non-null    int32
 7   Away Team Goals       836 non-null    int32
 8   Away Team Name        836 non-null    object
 9   Win conditions        836 non-null    object
 10  Attendance            836 non-null    int32
 11  Half-time Home Goals  836 non-null    int32
 12  Half-time Away Goals  836 non-null    int32
 13  Referee               836 non-null    object
 14  Assistant 1           836 non-null    object
 15  Assistant 2           836 non-null    object
 16  RoundID               836 non-null    int32
 17  MatchID               836 non-null    int32
 18  Home Team Initials    836 non-null    object
 19  Away Team Initials    836 non-null    object
dtypes: datetime64[ns](1), int32(8), object(11)
memory usage: 111.0+ KB

In [330]:
df_match.describe()

,Year,Datetime,Home Team Goals,Away Team Goals,Attendance,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID
count,836.000000,836,836.000000,836.000000,836.000000,836.000000,836.000000,8.360000e+02,8.360000e+02
mean,1984.535885,1985-01-01 20:22:19.593301440,1.824163,1.021531,44857.204545,0.718900,0.427033,1.086093e+07,5.677577e+07
min,1930.000000,1930-07-13 15:00:00,0.000000,0.000000,2000.000000,0.000000,0.000000,2.010000e+02,2.500000e+01
25%,1970.000000,1970-06-06 16:00:00,1.000000,0.000000,29800.000000,0.000000,0.000000,2.620000e+02,1.183500e+03
50%,1990.000000,1990-06-10 21:00:00,2.000000,1.000000,41061.500000,0.000000,0.000000,3.370000e+02,2.113500e+03
75%,2002.000000,2002-06-14 20:30:00,3.000000,2.000000,60984.500000,1.000000,1.000000,2.497220e+05,4.395005e+07
max,2014.000000,2014-07-13 16:00:00,10.000000,7.000000,173850.000000,6.000000,5.000000,9.741060e+07,3.001865e+08
std,22.299860,NaN,1.619178,1.072024,23537.091350,0.941995,0.675091,2.751802e+07,1.070329e+08

# Transformations

In [331]:
def get_condition(con):
    if con.find('extra time') != -1:
        return "ET"
    elif con.find('penalties') != -1:
        return "PEN"
    elif con.find('Golden Goal') != 1:
        return "GG"
    else:
        return ''
    
def get_winner(data):
    h_team = data[0]
    h_goals = data[2]
    a_team = data[1]
    a_goals = data[3]
    cond = data[4]
    stage = data[5]
    if cond != ' ':
        if cond.startswith(' win on penalties'):
            h_goals, a_goals = map(int, cond[cond.find('(') + 1 : cond.find(')')].split(' - '))
        elif cond.find('Golden Goal') == -1:
            return cond.split(' win')[0]
    if h_goals > a_goals:
        return h_team
    elif a_goals > h_goals:
        return a_team
    else:
        return "Draw"
    
def half_time_result(data):
    h_team = data[0]
    h_goals = data[2]
    a_team = data[1]
    a_goals = data[3]
    if h_goals > a_goals:
        return h_team
    elif a_goals > h_goals:
        return a_team
    else:
        return "Draw"
    
def clean_countries(name):
    name = re.sub(r'rn">', '', name)
    name = name.replace("IR Iran", "Iran")
    name = name.replace("Germany FR", "Germany")
    #name = name.replace("German DR", "Germany")
    return name

def clean_initials(name):
    #name = name.replace("GDR", "GER")
    name = name.replace("FRG", "GER")
    return name

def after_half_time(data):
    winner = data[0]
    ht_winner = data[1]
    if winner == ht_winner and winner != "Draw":
        return 'Maintained the lead'
    elif ht_winner != winner:
        return "Bottled the lead"
    else:
        return "Draw till the end"

In [332]:
df_match['Win condition'] = df_match[df_match['Win conditions'] != " "]['Win conditions'].apply(lambda x: get_condition(x))
df_match['Win condition'].fillna('', inplace=True)

In [333]:
df_match['Home Team Name'] = df_match['Home Team Name'].apply(clean_countries)
df_match['Away Team Name'] = df_match['Away Team Name'].apply(clean_countries)
df_match['Home Team Initials'] = df_match['Home Team Initials'].apply(clean_initials)
df_match['Away Team Initials'] = df_match['Away Team Initials'].apply(clean_initials)
df_match['Match Winner'] = df_match[['Home Team Name','Away Team Name', 'Home Team Goals', 'Away Team Goals', 'Win conditions', 'Stage']].apply(get_winner, axis=1)
df_match['Half time result'] = df_match[['Home Team Name','Away Team Name', 'Half-time Home Goals', 'Half-time Away Goals']].apply(half_time_result, axis=1)
df_match['After Half time'] = df_match[['Match Winner','Half time result']].apply(after_half_time, axis=1)

In [334]:
df_match[df_match['Win conditions'] != " "]['Stage'].value_counts()

Stage
Round of 16              21
Quarter-finals           15
Semi-finals               8
Final                     7
First round               3
Preliminary round         1
Group 1                   1
Match for third place     1
Name: count, dtype: int64

In [335]:
df_match['Stage'].replace(['Third place', 'Play-off for third place'], 'Match for third place', inplace=True)

In [336]:
df_match['Replayed'] = False
draw_not_allowed = ['First round', 'Quarter-finals', 'Semi-finals', 'Final', 'Match for third place']

In [337]:
df_match['Stage'].unique()

array(['Group 1', 'Group 4', 'Group 2', 'Group 3', 'Semi-finals', 'Final',
       'Preliminary round', 'Quarter-finals', 'Match for third place',
       'First round', 'Group 6', 'Group B', 'Group A', 'Group 5',
       'Group C', 'Group D', 'Group F', 'Group E', 'Round of 16',
       'Group H', 'Group G'], dtype=object)

In [338]:
df_match.loc[(df_match[['Year','Stage','Home Team Name','Away Team Name']].duplicated(keep=False)) & (df_match['Home Team Goals'] == df_match['Away Team Goals']) & (df_match['Stage'].isin(draw_not_allowed)), 'Replayed'] = True

In [339]:
df_match

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Win condition,Match Winner,Half time result,After Half time,Replayed
0,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,,France,France,Maintained the lead,False
1,1930,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL,,USA,USA,Maintained the lead,False
2,1930,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA,,Yugoslavia,Yugoslavia,Maintained the lead,False
3,1930,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER,,Romania,Romania,Maintained the lead,False
4,1930,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA,,Argentina,Draw,Bottled the lead,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,2014,2014-07-05 13:00:00,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1,0,Belgium,,68551,1,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255953,300186504,ARG,BEL,,Argentina,Argentina,Maintained the lead,False
832,2014,2014-06-29 13:00:00,Round of 16,Estadio Castelao,Fortaleza,Netherlands,2,1,Mexico,,58817,0,0,PROENCA Pedro (POR),MIRANDA Bertino (POR),TRIGO Jose (POR),255951,300186508,NED,MEX,,Netherlands,Draw,Bottled the lead,False
833,2014,2014-06-29 17:00:00,Round of 16,Arena Pernambuco,Recife,Costa Rica,1,1,Greece,Costa Rica win on penalties (5 - 3),41242,0,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255951,300186459,CRC,GRE,PEN,Costa Rica,Draw,Bottled the lead,False
834,2014,2014-07-01 13:00:00,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1,0,Switzerland,Argentina win after extra time,63255,0,0,ERIKSSON Jonas (SWE),KLASENIUS Mathias (SWE),WARNMARK Daniel (SWE),255951,300186503,ARG,SUI,ET,Argentina,Draw,Bottled the lead,False
835,2014,2014-07-01 17:00:00,Round of 16,Arena Fonte Nova,Salvador,Belgium,2,1,USA,Belgium win after extra time,51227,0,0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255951,300186497,BEL,USA,ET,Belgium,Draw,Bottled the lead,False

In [340]:
df_match.sort_values('Datetime', ascending=True, inplace=True)
#df_match.to_csv('WorldCupMatches_cleaned.csv', index=False)

# Players Dataframe

In [341]:
df_players

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN
...,...,...,...,...,...,...,...,...,...
37779,255959,300186501,ARG,SABELLA Alejandro (ARG),N,19,ALVAREZ,NaN,NaN
37780,255959,300186501,GER,LOEW Joachim (GER),N,6,KHEDIRA,NaN,NaN
37781,255959,300186501,ARG,SABELLA Alejandro (ARG),N,20,AGUERO,NaN,IH46' Y65'
37782,255959,300186501,GER,LOEW Joachim (GER),N,21,MUSTAFI,NaN,NaN
37783,255959,300186501,ARG,SABELLA Alejandro (ARG),N,23,BASANTA,NaN,NaN

In [342]:
df_players.isna().sum()

RoundID              0
MatchID              0
Team Initials        0
Coach Name           0
Line-up              0
Shirt Number         0
Player Name          0
Position         33641
Event            28715
dtype: int64

In [343]:
df_players.nunique()

RoundID           101
MatchID           836
Team Initials      82
Coach Name        335
Line-up             2
Shirt Number       24
Player Name      7663
Position            3
Event            1893
dtype: int64

In [ ]:
df_players.drop_duplicates(inplace=True)

# World Cups

In [344]:
df_cups

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [345]:
df_cups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            20 non-null     int64
 1   Country         20 non-null     object
 2   Winner          20 non-null     object
 3   Runners-Up      20 non-null     object
 4   Third           20 non-null     object
 5   Fourth          20 non-null     object
 6   GoalsScored     20 non-null     int64
 7   QualifiedTeams  20 non-null     int64
 8   MatchesPlayed   20 non-null     int64
 9   Attendance      20 non-null     object
dtypes: int64(4), object(6)
memory usage: 1.7+ KB

In [346]:
df_match['Match Winner'].value_counts()

Match Winner
Draw                      160
Brazil                     73
Germany                    68
Argentina                  46
Italy                      46
                         ...
Iran                        1
Korea DPR                   1
Tunisia                     1
Cuba                        1
Bosnia and Herzegovina      1
Name: count, Length: 65, dtype: int64

In [347]:
df_cups.nunique()

Year              20
Country           15
Winner             9
Runners-Up        10
Third             14
Fourth            16
GoalsScored       17
QualifiedTeams     5
MatchesPlayed      9
Attendance        20
dtype: int64

In [348]:
df_cups['Attendance'] = df_cups['Attendance'].apply(lambda x: int(x.replace('.','')))
df_cups['Winner'] = df_cups['Winner'].apply(clean_countries)
df_cups['Runners-Up'] = df_cups['Runners-Up'].apply(clean_countries)
df_cups['Third'] = df_cups['Third'].apply(clean_countries)
df_cups['Fourth'] = df_cups['Fourth'].apply(clean_countries)

In [349]:
df_cups

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1045246
4,1954,Switzerland,Germany,Hungary,Austria,Uruguay,140,16,26,768607
5,1958,Sweden,Brazil,Sweden,France,Germany,126,16,35,819810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893172
7,1966,England,England,Germany,Portugal,Soviet Union,89,16,32,1563135
8,1970,Mexico,Brazil,Italy,Germany,Uruguay,95,16,32,1603975
9,1974,Germany,Germany,Netherlands,Poland,Brazil,97,16,38,1865753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1545791
11,1982,Spain,Italy,Germany,Poland,France,146,24,52,2109723
12,1986,Mexico,Argentina,Germany,France,Belgium,132,24,52,2394031
13,1990,Italy,Germany,Argentina,Italy,England,115,24,52,2516215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2785100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2705197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810

In [350]:
df_cups['Average Attendance'] = (df_cups['Attendance'] / df_cups['MatchesPlayed']).astype(int)

In [351]:
df_cups

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance,Average Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590549,32808
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363000,21352
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375700,20872
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1045246,47511
4,1954,Switzerland,Germany,Hungary,Austria,Uruguay,140,16,26,768607,29561
5,1958,Sweden,Brazil,Sweden,France,Germany,126,16,35,819810,23423
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893172,27911
7,1966,England,England,Germany,Portugal,Soviet Union,89,16,32,1563135,48847
8,1970,Mexico,Brazil,Italy,Germany,Uruguay,95,16,32,1603975,50124
9,1974,Germany,Germany,Netherlands,Poland,Brazil,97,16,38,1865753,49098
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1545791,40678
11,1982,Spain,Italy,Germany,Poland,France,146,24,52,2109723,40571
12,1986,Mexico,Argentina,Germany,France,Belgium,132,24,52,2394031,46039
13,1990,Italy,Germany,Argentina,Italy,England,115,24,52,2516215,48388
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538,68991
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2785100,43517
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2705197,42268
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439,52491
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856,49669
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810,52918

In [352]:
#df_cups.to_csv('WorldCup_cleaned.csv', index=False)

In [353]:
#df_match.to_csv('WorldCupMatches_cleaned.csv', index=False)

# Creating Countrywise Stats

In [354]:
df_match['Stage'].unique()

array(['Group 1', 'Group 4', 'Group 2', 'Group 3', 'Semi-finals', 'Final',
       'Preliminary round', 'Quarter-finals', 'Match for third place',
       'First round', 'Group 6', 'Group B', 'Group A', 'Group 5',
       'Group D', 'Group C', 'Group F', 'Group E', 'Round of 16',
       'Group H', 'Group G'], dtype=object)

In [355]:
all_years = df_match['Year'].unique()
all_countries = df_match['Away Team Name'].sort_values().unique()
all_initials = df_match['Away Team Initials'].sort_values().unique().tolist()
df_players['Team Initials'].replace(['FRG'], 'GER', inplace=True)

In [356]:
def get_country_results(country):
    df_ctr = df_match[(df_match['Away Team Name'] == country) | (df_match['Home Team Name'] == country)].copy()
    last_row_per_year = df_ctr.groupby(pd.DatetimeIndex(df_ctr.Datetime).year).last()
    ctr_df = last_row_per_year.iloc[:, [0,2,5,8, -4]].copy()

    def get_yearly_result(data):
        yr, stage, ht, at, winner = data['Year'], data['Stage'], data['Home Team Name'], data['Away Team Name'], data['Match Winner']
        opp = at if ht == country else ht
        result, remarks = None, ''
        if stage == "Final":
            result = 'Champions' if winner == country else "Runners-up"
            remarks = ("Champions by beating " + opp + " in the final") if winner == country else ("Lost the final to " + opp)
        elif stage == "Match for third place":
            result = 'Third place' if winner == country else "Fourth place"
            remarks = ("Beaten " + opp + " to finish 3rd") if winner == country else ("Finished 4th behind " + opp)
        elif stage == 'Semi-finals':
            result = 'Fourth place'
            remarks = "Reached the Semifinal"
        elif stage.find('Group') != -1:
            result = 'Group stage'
            remarks = ("Eliminated in the group stages")
        elif stage == 'Round of 16' or stage == 'First round':
            result = 'Round of 16'
            remarks = ("Reached the round of 16") if winner == country else ("Eliminated by " + opp)
        else:
            result = stage
            remarks = ("Reached the " + stage) if winner == country else ("Eliminated by " + opp)
        
        return pd.Series([result, opp, remarks])

    ctr_df['Country'] = country
    initials = df_match[df_match['Away Team Name'] == country]['Away Team Initials'].unique()[0]
    ctr_df['Initials'] = initials
    ctr_df['Attendance'] = df_ctr.groupby('Year')['Attendance'].sum()
    ctr_df[['Result', 'Last opponent', 'Remarks']] = ctr_df.apply(get_yearly_result, axis=1)
    for year in all_years:
        if year not in ctr_df['Year'].values:
            nq_df = pd.DataFrame([[country, initials, year, 'Not qualified', '', 'Did not qualify for the tournament', np.nan]], 
                                 columns=['Country', 'Initials', 'Year', 'Result', 'Last opponent', 'Remarks', 'Attendance'])
            ctr_df = pd.concat([ctr_df, nq_df])
    ctr_df.sort_values('Year', inplace=True)
    ctr_df['Host'] = df_cups['Country'].values
    ctr_df = ctr_df.reset_index(drop=True)
    ctr_df = ctr_df[['Country', 'Initials', 'Host', 'Year', 'Attendance', 'Result', 'Last opponent', 'Remarks']]

    return ctr_df

In [357]:
df_country = pd.DataFrame(columns=['Country', 'Initials', 'Host', 'Year', 'Attendance', 'Result', 'Last opponent', 'Remarks'])

for country in all_countries:
    temp = get_country_results(country)
    df_country = pd.concat([df_country, temp])

df_country = df_country.reset_index(drop=True)

In [358]:
def get_statistics(dataset):
    dataset['Goals_scored'] = np.nan
    dataset['Goals_conceded'] = np.nan
    dataset['Matches'] = np.nan
    dataset['Wins'] = np.nan
    dataset['Draws'] = np.nan
    dataset['Losses'] = np.nan
    dataset['Win percentage'] = np.nan

    for i, val in dataset.iterrows():
        yr = val['Year']
        ctry = val['Country']
        if (dataset.loc[(dataset['Country'] == ctry) & (dataset['Year'] == yr), 'Result'].values[0] == 'Not qualified'):
            continue
        temp_dt = df_match[((df_match['Home Team Name'] == ctry) | (df_match['Away Team Name'] == ctry)) & (df_match['Year'] == yr)]
        res = temp_dt['Match Winner'].value_counts().to_dict()
        matches = temp_dt.shape[0]
        wins = res[ctry] if ctry in res.keys() else 0
        draws = res['Draw'] if 'Draw' in res.keys() else 0
        losses = matches - wins - draws
        temp_ht_df = df_match[(df_match['Home Team Name'] == ctry) & (df_match['Year'] == yr)]
        temp_at_df = df_match[(df_match['Away Team Name'] == ctry) & (df_match['Year'] == yr)]
        gs_year = temp_ht_df['Home Team Goals'].sum() + temp_at_df['Away Team Goals'].sum()
        gc_year = temp_ht_df['Away Team Goals'].sum() + temp_at_df['Home Team Goals'].sum()

        dataset.iloc[i, -7] = gs_year
        dataset.iloc[i, -6] = gc_year
        dataset.iloc[i, -5] = matches
        dataset.iloc[i, -4] = wins
        dataset.iloc[i, -3] = draws
        dataset.iloc[i, -2] = losses
        dataset.iloc[i, -1] = round(wins / matches * 100, 2)

    dataset['Goals_scored'] = dataset['Goals_scored'].astype('Int8')
    dataset['Goals_conceded'] = dataset['Goals_conceded'].astype('Int8')
    dataset['Matches'] = dataset['Matches'].astype('Int8')
    dataset['Wins'] = dataset['Wins'].astype('Int8')
    dataset['Draws'] = dataset['Draws'].astype('Int8')
    dataset['Losses'] = dataset['Losses'].astype('Int8')
    dataset['Attendance'] = dataset['Attendance'].astype('Int32')
    
    return dataset

df_country = get_statistics(df_country)

In [359]:
def get_coaches(data):
    yy, init = data['Year'], data['Initials']
    cur_ids = df_match[(df_match['Year'] == yy) & ((df_match['Home Team Initials'] == init) | (df_match['Away Team Initials'] == init))]['MatchID'].tolist()
    sliced = df_players[(df_players['MatchID'].isin(cur_ids)) & (df_players['Team Initials'] == init)]
    if sliced.shape[0] > 0:
        cur_mgr = sliced.groupby('Coach Name')['MatchID'].nunique().sort_values(ascending=False).index[0]
        return cur_mgr
    return ''
df_country['Coach'] = df_country.apply(get_coaches, axis=1)

In [360]:
cols = ['Comebacks', 'Bottled', 'Draw', 'HT victory', '2nd HF win', 'NT win', 'NT loss', 'NT draw', 'ET win', 'ET loss', 'GG win', 'GG loss', 'PEN win', 'PEN loss']
df_country[cols] = np.nan

In [361]:
for country in all_countries:
    for year in all_years:
        temp = df_match[((df_match['Away Team Name'] == country) | (df_match['Home Team Name'] == country)) & (df_match['Year'] == year)]
        comeback, bottled, just_draw, ht_win_maintain, won_in_2nd, nt_won, nt_lost, nt_draw, et_won, et_lost, gg_won, gg_lost, pen_won, pen_lost = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        for i, row in temp.iterrows():
            won, ht_won, win_con = row['Match Winner'], row['Half time result'], row['Win condition']
            if ht_won != country and ht_won != 'Draw' and won == country:
                comeback += 1
            elif ht_won == country and won == country:
                ht_win_maintain += 1
            elif ht_won == 'Draw' and won == country:
                won_in_2nd += 1
            elif ht_won == 'Draw' and won == 'Draw':
                just_draw += 1
            elif ht_won != 'Draw' and ht_won == country and won != country:
                bottled += 1

            if win_con == '' and won == country:
                nt_won += 1
            elif win_con == '' and won != country and won != 'Draw':
                nt_lost += 1
            elif win_con == '' and won == 'Draw':
                nt_draw += 1
            elif win_con == 'ET' and won == country:
                et_won += 1
            elif win_con == 'ET' and won != country:
                et_lost += 1
            elif win_con == 'PEN' and won == country:
                pen_won += 1
            elif win_con == 'PEN' and won != country:
                pen_lost += 1
            elif win_con == 'GG' and won == country:
                gg_won += 1
            elif win_con == 'GG' and won != country:
                gg_lost += 1

        temp_bool = (df_country['Country'] == country) & (df_country['Year'] == year) & ~(df_country['Result'] == 'Not qualified')
        df_country.loc[temp_bool, 'Comebacks'] = comeback
        df_country.loc[temp_bool, 'Bottled'] = bottled
        df_country.loc[temp_bool, 'Draw'] = just_draw
        df_country.loc[temp_bool, 'HT victory'] = ht_win_maintain
        df_country.loc[temp_bool, '2nd HF win'] = won_in_2nd

        df_country.loc[temp_bool, 'NT win'] = nt_won
        df_country.loc[temp_bool, 'NT loss'] = nt_lost
        df_country.loc[temp_bool, 'NT draw'] = nt_draw

        df_country.loc[temp_bool, 'ET win'] = et_won
        df_country.loc[temp_bool, 'ET loss'] = et_lost
        df_country.loc[temp_bool, 'GG win'] = gg_won
        df_country.loc[temp_bool, 'GG loss'] = gg_lost
        df_country.loc[temp_bool, 'PEN win'] = pen_won
        df_country.loc[temp_bool, 'PEN loss'] = pen_lost

df_country.loc[:, cols] = df_country.loc[:, cols].astype('Int8')

In [362]:
df_germany = df_country[df_country['Country'] == 'Germany'].copy()
df_argentina = df_country[df_country['Country'] == 'Argentina'].copy()

In [363]:
df_players[df_players['Team Initials'] == 'GER']['Player Name'].value_counts().nlargest(5)

Player Name
KLOSE          32
M�LLER         28
LAHM           25
MERTESACKER    25
PODOLSKI       25
Name: count, dtype: int64

In [364]:
ctry_match = (df_players['Team Initials'] == 'GER')
has_event = (~df_players['Event'].isna())
scored_goal = (~(df_players['Event'].isna()) & (df_players['Event'].str.count('G') > 0))

In [365]:
df_players[(df_players['Event'].str.count('Y') > 0)]

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
2915,209,1186,BRA,COSTA Flavio (BRA),S,0,BIGODE,NaN,Y1'
5857,231,1447,ARG,LORENZO Juan Carlos (ARG),S,15,Ruben NAVARRO,C,Y1'
7256,238,1596,BUL,VYTLACIL Rudolf (TCH),S,6,Dobromir JECHEV,NaN,Y1'
7257,238,1596,BRA,FEOLA Vicente (BRA),S,13,DENILSON,NaN,Y1'
7264,238,1596,BUL,VYTLACIL Rudolf (TCH),S,11,Ivan KOLEV,NaN,Y1'
...,...,...,...,...,...,...,...,...,...
37720,255957,300186502,BRA,SCOLARI Luiz Felipe (BRA),N,5,FERNANDINHO,NaN,IH46' Y54'
37740,255959,300186501,GER,LOEW Joachim (GER),S,4,H�WEDES,NaN,Y34'
37744,255959,300186501,GER,LOEW Joachim (GER),S,7,SCHWEINSTEIGER,NaN,Y29'
37753,255959,300186501,ARG,SABELLA Alejandro (ARG),S,14,MASCHERANO,NaN,Y64'
37781,255959,300186501,ARG,SABELLA Alejandro (ARG),N,20,AGUERO,NaN,IH46' Y65'

In [366]:
def get_goals_scored(data):
    if pd.notna(data):
        gs = data.count('G')
        if gs > 0:
            return gs

df_players['Goals'] = df_players['Event'].apply(get_goals_scored)

In [367]:
df_players.groupby('Player Name')['Goals'].count().nlargest(10)

Player Name
RONALDO                               13
KLOSE                                 12
Gerd MUELLER                           9
M�LLER                                 9
Uwe SEELER                             9
Grzegorz LATO                          8
Helmut RAHN                            8
JAIRZINHO                              8
PEL� (Edson Arantes do Nascimento)     8
BEBETO                                 6
Name: Goals, dtype: int64

In [368]:
df_players[df_players['Player Name'] == 'KLOSE'].shape

(32, 10)

In [369]:
df_players['Match Year'] = df_players['MatchID'].apply(lambda x: df_match[df_match['MatchID'] == int(x)]['Year'].values[0])

In [370]:
def get_clean_sheets(data, ctry):
    ht, at, hg, ag = data['Home Team Name'], data['Away Team Name'], data['Home Team Goals'], data['Away Team Goals']
    gc = ag if ht == ctry else hg
    return 1 if gc == 0 else 0

def clean_sheets(data):
    ctry, yr = data['Country'], data['Year']
    return df_match[((df_match['Home Team Name'] == ctry) | (df_match['Away Team Name'] == ctry)) & (df_match['Year'] == yr)].apply(lambda x: get_clean_sheets(x, ctry), axis=1).sum()

In [371]:
df_country['clean sheets'] = df_country.apply(clean_sheets, axis=1).astype('Int8')

In [372]:
events = df_players['Event'].unique().tolist()[1:]

In [373]:
def get_final(data):
    temp = df_match[(df_match['Stage'] == 'Final') & (df_match['Year'] == data)]
    if temp.shape[0] > 0:
        return temp['Stadium'].values[0] + ", " + temp['City'].values[0]

def get_final_attendance(data):
    temp = df_match[(df_match['Stage'] == 'Final') & (df_match['Year'] == data)]
    if temp.shape[0] > 0:
        return temp['Attendance'].values[0]

In [374]:
df_cups['Final venue'] = df_cups['Year'].apply(get_final)
df_cups['Attendance for the final'] = df_cups['Year'].apply(get_final_attendance).astype('Int32')

In [375]:
for event in events:
    if re.findall(r'^G.*\'$', event):
        print(re.search(r'^G.*\'$', event))

<regex.Match object; span=(0, 4), match="G40'">
<regex.Match object; span=(0, 4), match="G70'">
<regex.Match object; span=(0, 9), match="G43' G87'">
<regex.Match object; span=(0, 4), match="G19'">
<regex.Match object; span=(0, 4), match="G45'">
<regex.Match object; span=(0, 4), match="G23'">
<regex.Match object; span=(0, 4), match="G69'">
<regex.Match object; span=(0, 4), match="G30'">
<regex.Match object; span=(0, 4), match="G62'">
<regex.Match object; span=(0, 4), match="G21'">
<regex.Match object; span=(0, 3), match="G1'">
<regex.Match object; span=(0, 4), match="G89'">
<regex.Match object; span=(0, 4), match="G79'">
<regex.Match object; span=(0, 4), match="G75'">
<regex.Match object; span=(0, 4), match="G81'">
<regex.Match object; span=(0, 8), match="G3' G65'">
<regex.Match object; span=(0, 4), match="G65'">
<regex.Match object; span=(0, 4), match="G85'">
<regex.Match object; span=(0, 9), match="G60' G67'">
<regex.Match object; span=(0, 14), match="G10' G15' G50'">
<regex.Match object; span=(0, 4), match="G60'">
<regex.Match object; span=(0, 4), match="G53'">
<regex.Match object; span=(0, 9), match="G12' G55'">
<regex.Match object; span=(0, 13), match="G8' G17' G80'">
<regex.Match object; span=(0, 9), match="G67' G83'">
<regex.Match object; span=(0, 9), match="G37' G73'">
<regex.Match object; span=(0, 4), match="G35'">
<regex.Match object; span=(0, 3), match="G7'">
<regex.Match object; span=(0, 4), match="G24'">
<regex.Match object; span=(0, 4), match="G15'">
<regex.Match object; span=(0, 4), match="G51'">
<regex.Match object; span=(0, 9), match="G12' G13'">
<regex.Match object; span=(0, 4), match="G56'">
<regex.Match object; span=(0, 9), match="G69' G87'">
<regex.Match object; span=(0, 4), match="G20'">
<regex.Match object; span=(0, 9), match="G80' G85'">
<regex.Match object; span=(0, 9), match="G20' G31'">
<regex.Match object; span=(0, 14), match="G18' G67' G72'">
<regex.Match object; span=(0, 4), match="G61'">
<regex.Match object; span=(0, 3), match="G4'">
<regex.Match object; span=(0, 4), match="G57'">
<regex.Match object; span=(0, 4), match="G12'">
<regex.Match object; span=(0, 4), match="G68'">
<regex.Match object; span=(0, 4), match="G37'">
<regex.Match object; span=(0, 4), match="G93'">
<regex.Match object; span=(0, 4), match="G44'">
<regex.Match object; span=(0, 4), match="G18'">
<regex.Match object; span=(0, 5), match="G109'">
<regex.Match object; span=(0, 9), match="G35' G39'">
<regex.Match object; span=(0, 4), match="G11'">
<regex.Match object; span=(0, 9), match="G31' G61'">
<regex.Match object; span=(0, 4), match="G29'">
<regex.Match object; span=(0, 8), match="G7' G43'">
<regex.Match object; span=(0, 4), match="G66'">
<regex.Match object; span=(0, 4), match="G48'">
<regex.Match object; span=(0, 8), match="G9' G67'">
<regex.Match object; span=(0, 4), match="G49'">
<regex.Match object; span=(0, 9), match="G29' G43'">
<regex.Match object; span=(0, 14), match="G66' G70' G87'">
<regex.Match object; span=(0, 4), match="G25'">
<regex.Match object; span=(0, 4), match="G55'">
<regex.Match object; span=(0, 4), match="G63'">
<regex.Match object; span=(0, 4), match="G90'">
<regex.Match object; span=(0, 14), match="G18' G29' G64'">
<regex.Match object; span=(0, 9), match="G20' G69'">
<regex.Match object; span=(0, 4), match="G50'">
<regex.Match object; span=(0, 4), match="G67'">
<regex.Match object; span=(0, 4), match="G82'">
<regex.Match object; span=(0, 4), match="G78'">
<regex.Match object; span=(0, 9), match="G60' G63'">
<regex.Match object; span=(0, 3), match="G8'">
<regex.Match object; span=(0, 14), match="G21' G69' G80'">
<regex.Match object; span=(0, 8), match="G1' G42'">
<regex.Match object; span=(0, 4), match="G54'">
<regex.Match object; span=(0, 4), match="G27'">
<regex.Match object; span=(0, 4), match="G28'">
<regex.Match object; span=(0, 4), match="G95'">
<regex.Match object; span=(0, 4), match="G71'">
<regex.Match object; span=(0, 4), match="G43'">
<regex.Match object; span=(0, 4), match="G13'">
<regex.Match object; span=(0, 9), match="G28' G89'">
<regex.Match object; span=(0, 9), match="G35' G76'">
<regex.Match object; span=(0, 9), match="G16' G69'">
<regex.Match object; span=(0, 4), match="G38'">
<regex.Match object; span=(0, 5), match="G105'">
<regex.Match object; span=(0, 10), match="G44' G103'">
<regex.Match object; span=(0, 4), match="G88'">
<regex.Match object; span=(0, 4), match="G94'">
<regex.Match object; span=(0, 3), match="G2'">
<regex.Match object; span=(0, 4), match="G83'">
<regex.Match object; span=(0, 9), match="G44' G71'">
<regex.Match object; span=(0, 20), match="G53' G59' G89' G118'">
<regex.Match object; span=(0, 15), match="G18' G93' G104'">
<regex.Match object; span=(0, 5), match="G111'">
<regex.Match object; span=(0, 5), match="G118'">
<regex.Match object; span=(0, 9), match="G75' G78'">
<regex.Match object; span=(0, 4), match="G64'">
<regex.Match object; span=(0, 4), match="G42'">
<regex.Match object; span=(0, 13), match="G9' G81' G89'">
<regex.Match object; span=(0, 4), match="G80'">
<regex.Match object; span=(0, 14), match="G22' G37' G44'">
<regex.Match object; span=(0, 4), match="G84'">
<regex.Match object; span=(0, 9), match="G51' G72'">
<regex.Match object; span=(0, 4), match="G10'">
<regex.Match object; span=(0, 3), match="G9'">
<regex.Match object; span=(0, 9), match="G39' G85'">
<regex.Match object; span=(0, 4), match="G87'">
<regex.Match object; span=(0, 9), match="G63' G74'">
<regex.Match object; span=(0, 9), match="G16' G82'">
<regex.Match object; span=(0, 8), match="G6' G35'">
<regex.Match object; span=(0, 9), match="G30' G79'">
<regex.Match object; span=(0, 4), match="G39'">
<regex.Match object; span=(0, 4), match="G17'">
<regex.Match object; span=(0, 4), match="G34'">
<regex.Match object; span=(0, 9), match="G25' G69'">
<regex.Match object; span=(0, 4), match="G59'">
<regex.Match object; span=(0, 9), match="G17' G88'">
<regex.Match object; span=(0, 4), match="G32'">
<regex.Match object; span=(0, 3), match="G3'">
<regex.Match object; span=(0, 9), match="G23' G51'">
<regex.Match object; span=(0, 4), match="G74'">
<regex.Match object; span=(0, 4), match="G26'">
<regex.Match object; span=(0, 9), match="G23' G54'">
<regex.Match object; span=(0, 14), match="G14' G40' G51'">
<regex.Match object; span=(0, 9), match="G32' G60'">
<regex.Match object; span=(0, 4), match="G16'">
<regex.Match object; span=(0, 4), match="G47'">
<regex.Match object; span=(0, 9), match="G37' G39'">
<regex.Match object; span=(0, 4), match="G73'">
<regex.Match object; span=(0, 9), match="G39' G88'">
<regex.Match object; span=(0, 19), match="G17' G36' G52' G58'">
<regex.Match object; span=(0, 9), match="G31' G55'">
<regex.Match object; span=(0, 9), match="G77' G85'">
<regex.Match object; span=(0, 3), match="G5'">
<regex.Match object; span=(0, 4), match="G33'">
<regex.Match object; span=(0, 9), match="G34' G43'">
<regex.Match object; span=(0, 4), match="G52'">
<regex.Match object; span=(0, 4), match="G14'">
<regex.Match object; span=(0, 14), match="G24' G36' G50'">
<regex.Match object; span=(0, 9), match="G12' G89'">
<regex.Match object; span=(0, 9), match="G75' G83'">
<regex.Match object; span=(0, 9), match="G26' G63'">
<regex.Match object; span=(0, 9), match="G36' G91'">
<regex.Match object; span=(0, 8), match="G5' G71'">
<regex.Match object; span=(0, 9), match="G54' G85'">
<regex.Match object; span=(0, 9), match="G30' G83'">
<regex.Match object; span=(0, 14), match="G17' G47' G57'">
<regex.Match object; span=(0, 13), match="G4' G21' G24'">
<regex.Match object; span=(0, 18), match="G3' G21' G69' G78'">
<regex.Match object; span=(0, 4), match="G77'">
<regex.Match object; span=(0, 9), match="G52' G54'">
<regex.Match object; span=(0, 4), match="G76'">
<regex.Match object; span=(0, 9), match="G10' G30'">
<regex.Match object; span=(0, 14), match="G37' G64' G70'">
<regex.Match object; span=(0, 4), match="G58'">
<regex.Match object; span=(0, 14), match="G30' G60' G77'">
<regex.Match object; span=(0, 9), match="G12' G79'">
<regex.Match object; span=(0, 9), match="G14' G85'">
<regex.Match object; span=(0, 4), match="G46'">
<regex.Match object; span=(0, 14), match="G25' G27' G53'">
<regex.Match object; span=(0, 9), match="G16' G39'">
<regex.Match object; span=(0, 9), match="G26' G34'">
<regex.Match object; span=(0, 14), match="G17' G19' G60'">
<regex.Match object; span=(0, 8), match="G7' G88'">
<regex.Match object; span=(0, 9), match="G61' G89'">
<regex.Match object; span=(0, 4), match="G31'">
<regex.Match object; span=(0, 9), match="G75' G86'">
<regex.Match object; span=(0, 11), match="G109' G116'">
<regex.Match object; span=(0, 4), match="G22'">
<regex.Match object; span=(0, 9), match="G18' G84'">
<regex.Match object; span=(0, 3), match="G6'">
<regex.Match object; span=(0, 9), match="G17' G64'">
<regex.Match object; span=(0, 9), match="G32' G79'">
<regex.Match object; span=(0, 14), match="G24' G30' G67'">
<regex.Match object; span=(0, 9), match="G20' P44'">
<regex.Match object; span=(0, 9), match="G38' G89'">
<regex.Match object; span=(0, 8), match="G4' G85'">
<regex.Match object; span=(0, 9), match="G63' G88'">
<regex.Match object; span=(0, 9), match="G34' G55'">
<regex.Match object; span=(0, 8), match="G3' G77'">
<regex.Match object; span=(0, 9), match="G19' G60'">
<regex.Match object; span=(0, 9), match="G19' G46'">
<regex.Match object; span=(0, 9), match="G17' G40'">
<regex.Match object; span=(0, 9), match="G82' G89'">
<regex.Match object; span=(0, 9), match="G44' G99'">
<regex.Match object; span=(0, 9), match="G55' G63'">
<regex.Match object; span=(0, 14), match="G52' G64' G75'">
<regex.Match object; span=(0, 19), match="G16' G36' G78' G89'">
<regex.Match object; span=(0, 9), match="G55' G90'">
<regex.Match object; span=(0, 8), match="G9' G32'">
<regex.Match object; span=(0, 9), match="G44' G55'">
<regex.Match object; span=(0, 9), match="G19' R71'">
<regex.Match object; span=(0, 8), match="G8' G11'">
<regex.Match object; span=(0, 4), match="G72'">
<regex.Match object; span=(0, 12), match="G1' G6' G53'">
<regex.Match object; span=(0, 8), match="G8' G70'">
<regex.Match object; span=(0, 9), match="G72' G86'">
<regex.Match object; span=(0, 9), match="G25' G87'">
<regex.Match object; span=(0, 9), match="G20' G61'">
<regex.Match object; span=(0, 9), match="G65' G67'">
<regex.Match object; span=(0, 9), match="G31' G59'">
<regex.Match object; span=(0, 9), match="G80' P84'">
<regex.Match object; span=(0, 13), match="G9' G32' R83'">
<regex.Match object; span=(0, 9), match="G47' G78'">
<regex.Match object; span=(0, 9), match="G39' G52'">
<regex.Match object; span=(0, 9), match="G20' P77'">
<regex.Match object; span=(0, 9), match="G31' G88'">
<regex.Match object; span=(0, 8), match="G2' G67'">
<regex.Match object; span=(0, 9), match="G65' G79'">
<regex.Match object; span=(0, 9), match="G27' G85'">
<regex.Match object; span=(0, 9), match="G38' G75'">
<regex.Match object; span=(0, 9), match="G28' G85'">
<regex.Match object; span=(0, 9), match="G11' G83'">
<regex.Match object; span=(0, 19), match="G27' P43' G56' P59'">
<regex.Match object; span=(0, 9), match="G30' G80'">
<regex.Match object; span=(0, 16), match="G18' G101' G120'">
<regex.Match object; span=(0, 9), match="G49' O73'">
<regex.Match object; span=(0, 9), match="G61' G83'">
<regex.Match object; span=(0, 9), match="G12' G54'">
<regex.Match object; span=(0, 9), match="G65' G75'">
<regex.Match object; span=(0, 9), match="G14' G63'">
<regex.Match object; span=(0, 4), match="G86'">
<regex.Match object; span=(0, 14), match="G27' P52' G88'">
<regex.Match object; span=(0, 9), match="G45' G46'">
<regex.Match object; span=(0, 14), match="G19' G26' G39'">
<regex.Match object; span=(0, 9), match="G34' O72'">
<regex.Match object; span=(0, 9), match="G19' G67'">
<regex.Match object; span=(0, 9), match="G51' G74'">
<regex.Match object; span=(0, 9), match="G63' G76'">
<regex.Match object; span=(0, 9), match="G13' O68'">
<regex.Match object; span=(0, 9), match="G49' O81'">
<regex.Match object; span=(0, 9), match="G75' O80'">
<regex.Match object; span=(0, 9), match="G15' G52'">
<regex.Match object; span=(0, 4), match="G98'">
<regex.Match object; span=(0, 5), match="G104'">
<regex.Match object; span=(0, 9), match="G37' O84'">
<regex.Match object; span=(0, 8), match="G7' G86'">
<regex.Match object; span=(0, 8), match="G7' G62'">
<regex.Match object; span=(0, 8), match="G8' O70'">
<regex.Match object; span=(0, 9), match="G34' O67'">
<regex.Match object; span=(0, 13), match="G8' G30' G81'">
<regex.Match object; span=(0, 9), match="G17' G87'">
<regex.Match object; span=(0, 14), match="G30' G34' G50'">
<regex.Match object; span=(0, 9), match="G18' O57'">
<regex.Match object; span=(0, 9), match="G15' G68'">
<regex.Match object; span=(0, 9), match="G46' G77'">
<regex.Match object; span=(0, 9), match="G38' O78'">
<regex.Match object; span=(0, 9), match="G10' G90'">
<regex.Match object; span=(0, 9), match="G50' O85'">
<regex.Match object; span=(0, 9), match="G14' O80'">
<regex.Match object; span=(0, 8), match="G1' O74'">
<regex.Match object; span=(0, 8), match="G9' O80'">
<regex.Match object; span=(0, 9), match="G43' O82'">
<regex.Match object; span=(0, 9), match="G71' G77'">
<regex.Match object; span=(0, 9), match="G36' O83'">
<regex.Match object; span=(0, 9), match="G44' G89'">
<regex.Match object; span=(0, 9), match="G38' G73'">
<regex.Match object; span=(0, 9), match="G60' O89'">
<regex.Match object; span=(0, 4), match="G41'">
<regex.Match object; span=(0, 9), match="G42' O75'">
<regex.Match object; span=(0, 9), match="G43' G84'">
<regex.Match object; span=(0, 9), match="G41' O66'">
<regex.Match object; span=(0, 9), match="G36' G53'">
<regex.Match object; span=(0, 8), match="G6' O66'">
<regex.Match object; span=(0, 9), match="G15' G28'">
<regex.Match object; span=(0, 9), match="G16' G71'">
<regex.Match object; span=(0, 9), match="G66' G87'">
<regex.Match object; span=(0, 9), match="G57' G63'">
<regex.Match object; span=(0, 9), match="G21' G48'">
<regex.Match object; span=(0, 9), match="G50' G72'">
<regex.Match object; span=(0, 5), match="G115'">
<regex.Match object; span=(0, 10), match="G38' G105'">
<regex.Match object; span=(0, 14), match="G23' Y32' G54'">
<regex.Match object; span=(0, 9), match="G29' G32'">
<regex.Match object; span=(0, 14), match="G54' Y83' O88'">
<regex.Match object; span=(0, 8), match="G1' G67'">
<regex.Match object; span=(0, 9), match="G28' G57'">
<regex.Match object; span=(0, 9), match="G24' O79'">
<regex.Match object; span=(0, 13), match="G9' G57' G66'">
<regex.Match object; span=(0, 9), match="G43' O81'">
<regex.Match object; span=(0, 9), match="G55' O74'">
<regex.Match object; span=(0, 9), match="G84' O88'">
<regex.Match object; span=(0, 9), match="G15' O71'">
<regex.Match object; span=(0, 9), match="G54' O67'">
<regex.Match object; span=(0, 9), match="G70' O75'">
<regex.Match object; span=(0, 9), match="G28' G31'">
<regex.Match object; span=(0, 8), match="G7' G31'">
<regex.Match object; span=(0, 9), match="G10' O69'">
<regex.Match object; span=(0, 9), match="G39' O85'">
<regex.Match object; span=(0, 13), match="G4' G26' G53'">
<regex.Match object; span=(0, 9), match="G27' G75'">
<regex.Match object; span=(0, 9), match="G11' O83'">
<regex.Match object; span=(0, 9), match="G33' G80'">
<regex.Match object; span=(0, 14), match="G46' G68' O83'">
<regex.Match object; span=(0, 13), match="G5' G25' G74'">
<regex.Match object; span=(0, 9), match="G22' G73'">
<regex.Match object; span=(0, 4), match="G92'">
<regex.Match object; span=(0, 5), match="G108'">
<regex.Match object; span=(0, 8), match="G2' O72'">
<regex.Match object; span=(0, 8), match="G6' G46'">
<regex.Match object; span=(0, 9), match="G59' O71'">
<regex.Match object; span=(0, 13), match="G6' Y79' O81'">
<regex.Match object; span=(0, 9), match="G45' O66'">
<regex.Match object; span=(0, 8), match="G4' O80'">
<regex.Match object; span=(0, 9), match="G11' O58'">
<regex.Match object; span=(0, 9), match="G18' O78'">
<regex.Match object; span=(0, 8), match="G3' O77'">
<regex.Match object; span=(0, 9), match="G68' O74'">
<regex.Match object; span=(0, 9), match="G16' O67'">
<regex.Match object; span=(0, 14), match="G11' G67' G80'">
<regex.Match object; span=(0, 9), match="G52' O81'">
<regex.Match object; span=(0, 9), match="G29' O71'">
<regex.Match object; span=(0, 9), match="G58' O62'">
<regex.Match object; span=(0, 9), match="G17' G73'">
<regex.Match object; span=(0, 9), match="G50' G76'">
<regex.Match object; span=(0, 9), match="G19' G27'">
<regex.Match object; span=(0, 18), match="G9' G14' G34' O86'">
<regex.Match object; span=(0, 9), match="G15' G87'">
<regex.Match object; span=(0, 5), match="G110'">
<regex.Match object; span=(0, 15), match="G27' G70' P111'">
<regex.Match object; span=(0, 5), match="G102'">
<regex.Match object; span=(0, 9), match="G79' Y83'">
<regex.Match object; span=(0, 9), match="G15' O85'">
<regex.Match object; span=(0, 9), match="G31' G72'">
<regex.Match object; span=(0, 9), match="G56' O80'">
<regex.Match object; span=(0, 19), match="G43' G57' G80' P89'">
<regex.Match object; span=(0, 9), match="G51' G55'">
<regex.Match object; span=(0, 9), match="G51' G63'">
<regex.Match object; span=(0, 9), match="G84' O90'">
<regex.Match object; span=(0, 19), match="G41' Y44' P55' O87'">
<regex.Match object; span=(0, 9), match="G26' G78'">
<regex.Match object; span=(0, 9), match="G40' G63'">
<regex.Match object; span=(0, 9), match="G28' G64'">
<regex.Match object; span=(0, 8), match="G9' O83'">
<regex.Match object; span=(0, 9), match="G46' O82'">
<regex.Match object; span=(0, 9), match="G35' G75'">
<regex.Match object; span=(0, 9), match="G37' O72'">
<regex.Match object; span=(0, 9), match="G43' Y68'">
<regex.Match object; span=(0, 14), match="G23' G61' G81'">
<regex.Match object; span=(0, 10), match="G15' OH46'">
<regex.Match object; span=(0, 9), match="G68' O72'">
<regex.Match object; span=(0, 9), match="G20' Y75'">
<regex.Match object; span=(0, 10), match="G22' OH46'">
<regex.Match object; span=(0, 13), match="G9' G46' Y76'">
<regex.Match object; span=(0, 9), match="G63' O84'">
<regex.Match object; span=(0, 14), match="G12' G63' G82'">
<regex.Match object; span=(0, 9), match="G51' O77'">
<regex.Match object; span=(0, 9), match="G78' G93'">
<regex.Match object; span=(0, 9), match="G67' Y82'">
<regex.Match object; span=(0, 10), match="G60' Y110'">
<regex.Match object; span=(0, 9), match="G51' O63'">
<regex.Match object; span=(0, 9), match="G44' O58'">
<regex.Match object; span=(0, 9), match="G11' O68'">
<regex.Match object; span=(0, 19), match="G15' Y39' G89' O90'">
<regex.Match object; span=(0, 9), match="G31' O81'">
<regex.Match object; span=(0, 9), match="G18' Y61'">
<regex.Match object; span=(0, 13), match="G2' G44' P90'">
<regex.Match object; span=(0, 9), match="G60' O83'">
<regex.Match object; span=(0, 9), match="G55' Y73'">
<regex.Match object; span=(0, 9), match="G14' O64'">
<regex.Match object; span=(0, 9), match="G16' O71'">
<regex.Match object; span=(0, 9), match="G65' G72'">
<regex.Match object; span=(0, 9), match="G52' I66'">
<regex.Match object; span=(0, 9), match="G42' G65'">
<regex.Match object; span=(0, 9), match="G45' Y75'">
<regex.Match object; span=(0, 14), match="G21' G28' Y54'">
<regex.Match object; span=(0, 8), match="G8' O56'">
<regex.Match object; span=(0, 9), match="G18' Y73'">
<regex.Match object; span=(0, 14), match="G44' Y58' O78'">
<regex.Match object; span=(0, 14), match="G12' Y28' G37'">
<regex.Match object; span=(0, 14), match="G66' G70' Y90'">
<regex.Match object; span=(0, 24), match="G15' G41' P44' G72' G75'">
<regex.Match object; span=(0, 8), match="G5' O63'">
<regex.Match object; span=(0, 9), match="G45' O83'">
<regex.Match object; span=(0, 8), match="G6' G40'">
<regex.Match object; span=(0, 9), match="G11' O85'">
<regex.Match object; span=(0, 9), match="G15' O76'">
<regex.Match object; span=(0, 9), match="G51' G88'">
<regex.Match object; span=(0, 9), match="G58' O85'">
<regex.Match object; span=(0, 19), match="G11' G18' Y84' O88'">

In [376]:
df_country.to_csv('WorldCupCountries.csv', index=False)
df_players.to_csv('WorldCupPlayers_cleaned.csv', index=False)

In [377]:
df_germany

,Country,Initials,Host,Year,Attendance,Result,Last opponent,Remarks,Goals_scored,Goals_conceded,Matches,Wins,Draws,Losses,Win percentage,Coach,Comebacks,Bottled,Draw,HT victory,2nd HF win,NT win,NT loss,NT draw,ET win,ET loss,GG win,GG loss,PEN win,PEN loss
580,Germany,GER,Uruguay,1930,<NA>,Not qualified,,Did not qualify for the tournament,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
581,Germany,GER,Italy,1934,33000,Third place,Austria,Beaten Austria to finish 3rd,11,8,4,3,0,1,75.00,NERZ Otto (GER),1,0,0,1,1,3,1,0,0,0,0,0,0,0
582,Germany,GER,France,1938,47177,Round of 16,Switzerland,Eliminated by Switzerland,3,5,2,0,1,1,0.00,HERBERGER Sepp (FRG),0,1,1,0,0,0,1,1,0,0,0,0,0,0
583,Germany,GER,Brazil,1950,<NA>,Not qualified,,Did not qualify for the tournament,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
584,Germany,GER,Switzerland,1954,238500,Champions,Hungary,Champions by beating Hungary in the final,25,14,6,5,0,1,83.33,HERBERGER Sepp (FRG),0,0,0,3,2,5,1,0,0,0,0,0,0,0
585,Germany,GER,Sweden,1958,180155,Fourth place,France,Finished 4th behind France,12,14,6,2,2,2,33.33,HERBERGER Sepp (FRG),0,0,1,2,0,2,2,2,0,0,0,0,0,0
586,Germany,GER,Chile,1962,260910,Quarter-finals,Yugoslavia,Eliminated by Yugoslavia,4,2,4,2,1,1,50.00,HERBERGER Sepp (FRG),0,0,1,2,0,2,1,1,0,0,0,0,0,0
587,Germany,GER,England,1966,300105,Runners-up,England,Lost the final to England,15,6,6,4,1,1,66.67,SCHOEN Helmut (FRG),0,0,1,3,1,4,0,1,0,1,0,0,0,0
588,Germany,GER,Mexico,1970,273731,Third place,Uruguay,Beaten Uruguay to finish 3rd,17,10,6,4,0,2,66.67,SCHOEN Helmut (FRG),1,0,0,3,0,4,0,0,0,2,0,0,0,0
589,Germany,GER,Germany,1974,469985,Champions,Netherlands,Champions by beating Netherlands in the final,13,4,7,6,0,1,85.71,SCHOEN Helmut (FRG),1,0,0,4,1,6,1,0,0,0,0,0,0,0
590,Germany,GER,Argentina,1978,280119,Group stage,Austria,Eliminated in the group stages,10,5,6,1,4,1,16.67,SCHOEN Helmut (FRG),0,1,4,1,0,1,1,4,0,0,0,0,0,0
591,Germany,GER,Spain,1982,450089,Runners-up,Italy,Lost the final to Italy,12,10,7,4,1,2,57.14,DERWALL Jupp (GER),0,0,1,2,2,3,2,1,0,0,0,0,1,0
592,Germany,GER,Mexico,1986,317600,Runners-up,Argentina,Lost the final to Argentina,8,7,7,3,1,3,42.86,BECKENBAUER Franz (GER),0,0,0,1,2,3,2,1,0,0,0,0,0,1
593,Germany,GER,Italy,1990,502581,Champions,Argentina,Champions by beating Argentina in the final,15,5,7,6,1,0,85.71,BECKENBAUER Franz (GER),0,0,1,3,3,5,0,1,0,0,0,0,1,0
594,Germany,GER,USA,1994,322474,Quarter-finals,Bulgaria,Eliminated by Bulgaria,9,7,5,3,1,1,60.00,VOGTS Berti (GER),0,0,0,2,1,3,1,1,0,0,0,0,0,0
595,Germany,GER,France,1998,182300,Quarter-finals,Croatia,Eliminated by Croatia,8,6,5,3,1,1,60.00,VOGTS Berti (GER),0,0,0,1,2,3,1,1,0,0,0,0,0,0
596,Germany,GER,Korea/Japan,2002,311955,Runners-up,Brazil,Lost the final to Brazil,14,3,7,5,1,1,71.43,VOELLER Rudi (GER),0,1,0,2,3,5,1,1,0,0,0,0,0,0
597,Germany,GER,Germany,2006,458000,Third place,Portugal,Beaten Portugal to finish 3rd,14,6,7,6,0,1,85.71,J�rgen KLINSMANN (GER),0,0,0,3,3,5,0,0,0,1,0,0,1,0
598,Germany,GER,South Africa,2010,386169,Third place,Uruguay,Beaten Uruguay to finish 3rd,16,5,7,5,0,2,71.43,LOEW Joachim (GER),0,0,0,3,2,5,2,0,0,0,0,0,0,0
599,Germany,GER,Brazil,2014,402673,Champions,Argentina,Champions by beating Argentina in the final,18,4,7,6,1,0,85.71,LOEW Joachim (GER),0,0,1,3,3,4,0,1,2,0,0,0,0,0

In [497]:
df_events = df_country[['Country', 'Initials', 'Year']].copy()

In [498]:
minute_cols = ['0-15', '16-30', '31-45', '46-60', '61-75', '76-90', 'ET']

In [499]:
minutes_data = []

for i, data in df_events.iterrows():
    ctry, yr = data['Initials'], data['Year']
    temp = df_players[(df_players['Team Initials'] == ctry) & (df_players['Match Year'] == yr)]
    if temp.shape[0] > 0:
        gs_min = [0] * 7
        for evt in temp['Event']:
            if pd.notna(evt):
                for i in re.findall(r"G(.*?)\'", evt):
                    i = int(i)
                    if i <= 15:
                        gs_min[0] += 1
                    elif i <= 30:
                        gs_min[1] += 1
                    elif i <= 45:
                        gs_min[2] += 1
                    elif i <= 60:
                        gs_min[3] += 1
                    elif i <= 75:
                        gs_min[4] += 1
                    elif i <= 90:
                        gs_min[5] += 1
                    else:
                        gs_min[6] += 1
        minutes_data.append(gs_min)
    else:
        minutes_data.append([np.nan]*7)

In [500]:
df_events = pd.concat([df_events, pd.DataFrame(minutes_data, columns = minute_cols).astype('Int8')], axis=1)
df_events_germany = df_events[df_events['Country'] == 'Germany']

In [501]:
df_events_germany

     Country Initials  Year  0-15  16-30  31-45  46-60  61-75  76-90    ET
580  Germany      GER  1930  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  <NA>
581  Germany      GER  1934     1      2      1      2      4      1     0
582  Germany      GER  1938     1      1      0      0      0      0     0
583  Germany      GER  1950  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  <NA>
584  Germany      GER  1954     4      3      1      4      2      8     0
585  Germany      GER  1958     1      3      2      2      1      3     0
586  Germany      GER  1962     0      0      1      1      0      1     0
587  Germany      GER  1966     3      1      3      1      3      3     0
588  Germany      GER  1970     0      5      1      1      2      4     3
589  Germany      GER  1974     1      1      3      3      0      3     0
590  Germany      GER  1978     2      2      2      0      3      1     0
591  Germany      GER  1982     2      1      0      2      3      2     2
592  Germany      GER  1986     1      1      0      1      1      4     0
593  Germany      GER  1990     0      1      3      4      3      2     0
594  Germany      GER  1994     3      1      2      1      1      0     0
595  Germany      GER  1998     1      0      0      2      2      2     0
596  Germany      GER  2002     0      3      3      1      3      4     0
597  Germany      GER  2006     4      1      1      2      1      4     0
598  Germany      GER  2010     2      3      1      2      6      2     0
599  Germany      GER  2014     4      8      2      2      3      3     6

In [450]:
pattern = r'G(.*?)\''

In [456]:
test

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goals,Match Year
34610,255931,300186475,GER,LOEW Joachim (GER),S,1,NEUER,GK,NaN,NaN,2014
34612,255931,300186475,GER,LOEW Joachim (GER),S,4,H�WEDES,NaN,NaN,NaN,2014
34614,255931,300186475,GER,LOEW Joachim (GER),S,5,HUMMELS,NaN,G32' O73',1.0,2014
34616,255931,300186475,GER,LOEW Joachim (GER),S,6,KHEDIRA,NaN,NaN,NaN,2014
34618,255931,300186475,GER,LOEW Joachim (GER),S,8,�ZIL,NaN,O63',NaN,2014
...,...,...,...,...,...,...,...,...,...,...,...
37774,255959,300186501,GER,LOEW Joachim (GER),N,15,DURM,NaN,NaN,NaN,2014
37776,255959,300186501,GER,LOEW Joachim (GER),N,17,MERTESACKER,NaN,I120',NaN,2014
37778,255959,300186501,GER,LOEW Joachim (GER),N,19,G�TZE,NaN,I88' G113',1.0,2014
37780,255959,300186501,GER,LOEW Joachim (GER),N,6,KHEDIRA,NaN,NaN,NaN,2014
37782,255959,300186501,GER,LOEW Joachim (GER),N,21,MUSTAFI,NaN,NaN,NaN,2014

In [502]:
test[test['MatchID']==300186501]

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goals,Match Year
36680,255959,300186501,GER,LOEW Joachim (GER),S,1,NEUER,GK,NaN,NaN,2014
36682,255959,300186501,GER,LOEW Joachim (GER),S,4,H�WEDES,NaN,Y34',NaN,2014
36684,255959,300186501,GER,LOEW Joachim (GER),S,5,HUMMELS,NaN,NaN,NaN,2014
36686,255959,300186501,GER,LOEW Joachim (GER),S,7,SCHWEINSTEIGER,NaN,Y29',NaN,2014
36688,255959,300186501,GER,LOEW Joachim (GER),S,8,�ZIL,NaN,O120',NaN,2014
36690,255959,300186501,GER,LOEW Joachim (GER),S,11,KLOSE,NaN,O88',NaN,2014
36692,255959,300186501,GER,LOEW Joachim (GER),S,13,M�LLER,NaN,NaN,NaN,2014
36694,255959,300186501,GER,LOEW Joachim (GER),S,16,LAHM,C,NaN,NaN,2014
36696,255959,300186501,GER,LOEW Joachim (GER),S,18,KROOS,NaN,NaN,NaN,2014
36698,255959,300186501,GER,LOEW Joachim (GER),S,20,BOATENG,NaN,NaN,NaN,2014
36700,255959,300186501,GER,LOEW Joachim (GER),S,23,KRAMER,NaN,O31',NaN,2014
36702,255959,300186501,GER,LOEW Joachim (GER),N,12,ZIELER,GK,NaN,NaN,2014
36704,255959,300186501,GER,LOEW Joachim (GER),N,22,WEIDENFELLER,GK,NaN,NaN,2014
36706,255959,300186501,GER,LOEW Joachim (GER),N,2,GRO�KREUTZ,NaN,NaN,NaN,2014
36708,255959,300186501,GER,LOEW Joachim (GER),N,3,GINTER,NaN,NaN,NaN,2014
36710,255959,300186501,GER,LOEW Joachim (GER),N,9,SCH�RRLE,NaN,I31',NaN,2014
36712,255959,300186501,GER,LOEW Joachim (GER),N,10,PODOLSKI,NaN,NaN,NaN,2014
36714,255959,300186501,GER,LOEW Joachim (GER),N,14,DRAXLER,NaN,NaN,NaN,2014
36716,255959,300186501,GER,LOEW Joachim (GER),N,15,DURM,NaN,NaN,NaN,2014
36718,255959,300186501,GER,LOEW Joachim (GER),N,17,MERTESACKER,NaN,I120',NaN,2014
36720,255959,300186501,GER,LOEW Joachim (GER),N,19,G�TZE,NaN,I88' G113',1.0,2014
36722,255959,300186501,GER,LOEW Joachim (GER),N,6,KHEDIRA,NaN,NaN,NaN,2014
36724,255959,300186501,GER,LOEW Joachim (GER),N,21,MUSTAFI,NaN,NaN,NaN,2014
37738,255959,300186501,GER,LOEW Joachim (GER),S,1,NEUER,GK,NaN,NaN,2014
37740,255959,300186501,GER,LOEW Joachim (GER),S,4,H�WEDES,NaN,Y34',NaN,2014
37742,255959,300186501,GER,LOEW Joachim (GER),S,5,HUMMELS,NaN,NaN,NaN,2014
37744,255959,300186501,GER,LOEW Joachim (GER),S,7,SCHWEINSTEIGER,NaN,Y29',NaN,2014
37746,255959,300186501,GER,LOEW Joachim (GER),S,8,�ZIL,NaN,O120',NaN,2014
37748,255959,300186501,GER,LOEW Joachim (GER),S,11,KLOSE,NaN,O88',NaN,2014
37750,255959,300186501,GER,LOEW Joachim (GER),S,13,M�LLER,NaN,NaN,NaN,2014
37752,255959,300186501,GER,LOEW Joachim (GER),S,16,LAHM,C,NaN,NaN,2014
37754,255959,300186501,GER,LOEW Joachim (GER),S,18,KROOS,NaN,NaN,NaN,2014
37756,255959,300186501,GER,LOEW Joachim (GER),S,20,BOATENG,NaN,NaN,NaN,2014
37758,255959,300186501,GER,LOEW Joachim (GER),S,23,KRAMER,NaN,O31',NaN,2014
37760,255959,300186501,GER,LOEW Joachim (GER),N,12,ZIELER,GK,NaN,NaN,2014
37762,255959,300186501,GER,LOEW Joachim (GER),N,22,WEIDENFELLER,GK,NaN,NaN,2014
37764,255959,300186501,GER,LOEW Joachim (GER),N,2,GRO�KREUTZ,NaN,NaN,NaN,2014
37766,255959,300186501,GER,LOEW Joachim (GER),N,3,GINTER,NaN,NaN,NaN,2014
37768,255959,300186501,GER,LOEW Joachim (GER),N,9,SCH�RRLE,NaN,I31',NaN,2014
37770,255959,300186501,GER,LOEW Joachim (GER),N,10,PODOLSKI,NaN,NaN,NaN,2014
37772,255959,300186501,GER,LOEW Joachim (GER),N,14,DRAXLER,NaN,NaN,NaN,2014
37774,255959,300186501,GER,LOEW Joachim (GER),N,15,DURM,NaN,NaN,NaN,2014
37776,255959,300186501,GER,LOEW Joachim (GER),N,17,MERTESACKER,NaN,I120',NaN,2014
37778,255959,300186501,GER,LOEW Joachim (GER),N,19,G�TZE,NaN,I88' G113',1.0,2014
37780,255959,300186501,GER,LOEW Joachim (GER),N,6,KHEDIRA,NaN,NaN,NaN,2014
37782,255959,300186501,GER,LOEW Joachim (GER),N,21,MUSTAFI,NaN,NaN,NaN,2014

### events = G:goal, I:subbed in O:subbed out Y:yellow card IH:in at halftime OH:out at halftime

In [463]:
gs_min = [0] * 7
for evt in test['Event']:
    if pd.notna(evt):
        for i in re.findall(r"G(.*?)\'", evt):
            i = int(i)
            if i <= 15:
                gs_min[0] += 1
            elif i <= 30:
                gs_min[1] += 1
            elif i <= 45:
                gs_min[2] += 1
            elif i <= 60:
                gs_min[3] += 1
            elif i <= 75:
                gs_min[4] += 1
            elif i <= 90:
                gs_min[5] += 1
            else:
                gs_min[6] += 1

In [464]:
gs_min

[4, 8, 2, 2, 3, 3, 6]

In [422]:
df_events_germany.apply(minutes_scored, axis=1)

Empty DataFrame
Columns: [RoundID, MatchID, Team Initials, Coach Name, Line-up, Shirt Number, Player Name, Position, Event, Goals, Match Year]
Index: []
      RoundID  MatchID Team Initials       Coach Name Line-up  Shirt Number
851       204     1108           GER  NERZ Otto (GER)       S             0  \
853       204     1108           GER  NERZ Otto (GER)       S             0
855       204     1108           GER  NERZ Otto (GER)       S             0
857       204     1108           GER  NERZ Otto (GER)       S             0
859       204     1108           GER  NERZ Otto (GER)       S             0
...       ...      ...           ...              ...     ...           ...
1339     3491     1105           GER  NERZ Otto (GER)       N             0
1341     3491     1105           GER  NERZ Otto (GER)       N             0
1343     3491     1105           GER  NERZ Otto (GER)       N             0
1345     3491     1105           GER  NERZ Otto (GER)       N             0
1347     3491     1105           GER  NERZ Otto (GER)       N             0

               Player Name Position Event  Goals  Match Year
851        Willibald KRESS       GK   NaN    NaN        1934
853          Ernest LEHNER      NaN   NaN    NaN        1934
855          Hans SCHWARTZ      NaN   NaN    NaN        1934
857          Otto SIFFLING      NaN  G49'    1.0        1934
859           Fritz SZEPAN        C   NaN    NaN        1934
...                    ...      ...   ...    ...         ...
1339        Ernst ALBRECHT      NaN   NaN    NaN        1934
1341          Rudolf NOACK      NaN   NaN    NaN        1934
1343         Hans SCHWARTZ      NaN   NaN    NaN        1934
1345  Stanislaus KOBIERSKI      NaN   NaN    NaN        1934
1347       Willibald KRESS      NaN   NaN    NaN        1934

[88 rows x 11 columns]
      RoundID  MatchID Team Initials            Coach Name Line-up
1390      206     1165           GER  HERBERGER Sepp (FRG)       S  \
1392      206     1165           GER  HERBERGER Sepp (FRG)       S
1394      206     1165           GER  HERBERGER Sepp (FRG)       S
1396      206     1165           GER  HERBERGER Sepp (FRG)       S
1398      206     1165           GER  HERBERGER Sepp (FRG)       S
1400      206     1165           GER  HERBERGER Sepp (FRG)       S
1402      206     1165           GER  HERBERGER Sepp (FRG)       S
1404      206     1165           GER  HERBERGER Sepp (FRG)       S
1406      206     1165           GER  HERBERGER Sepp (FRG)       S
1408      206     1165           GER  HERBERGER Sepp (FRG)       S
1410      206     1165           GER  HERBERGER Sepp (FRG)       S
1412      206     1165           GER  HERBERGER Sepp (FRG)       N
1414      206     1165           GER  HERBERGER Sepp (FRG)       N
1416      206     1165           GER  HERBERGER Sepp (FRG)       N
1418      206     1165           GER  HERBERGER Sepp (FRG)       N
1420      206     1165           GER  HERBERGER Sepp (FRG)       N
1422      206     1165           GER  HERBERGER Sepp (FRG)       N
1424      206     1165           GER  HERBERGER Sepp (FRG)       N
1426      206     1165           GER  HERBERGER Sepp (FRG)       N
1428      206     1165           GER  HERBERGER Sepp (FRG)       N
1430      206     1165           GER  HERBERGER Sepp (FRG)       N
1432      206     1165           GER  HERBERGER Sepp (FRG)       N
1719      206     1166           GER  HERBERGER Sepp (FRG)       S
1721      206     1166           GER  HERBERGER Sepp (FRG)       S
1723      206     1166           GER  HERBERGER Sepp (FRG)       S
1725      206     1166           GER  HERBERGER Sepp (FRG)       S
1727      206     1166           GER  HERBERGER Sepp (FRG)       S
1729      206     1166           GER  HERBERGER Sepp (FRG)       S
1731      206     1166           GER  HERBERGER Sepp (FRG)       S
1733      206     1166           GER  HERBERGER Sepp (FRG)       S
1735      206     1166           GER  HERBERGER Sepp (FRG)       S
1737      206     1166           GER  HERBERGER Sepp (FRG)       S
1739      206     1166           GER  HERBERGER Sepp (FRG)       S
1741      206     1166           GER  HERBERGER Sepp (FRG)       N
1743      206     1166           GER  HERBERGER Sepp (FRG)       N
1745      206     1166           GER  HERBERGER Sepp (FRG)       N
1747      206     1166           GER  HERBERGER Sepp (FRG)       N
1749      206     1166           GER  HERBERGER Sepp (FRG)       N
1751      206     1166           GER  HERBERGER Sepp (FRG)       N
1753      206     1166           GER  HERBERGER Sepp (FRG)       N
1755      206     1166           GER  HERBERGER Sepp (FRG)       N
1757      206     1166           GER  HERBERGER Sepp (FRG)       N
1759      206     1166           GER  HERBERGER Sepp (FRG)       N
1761      206     1166           GER  HERBERGER Sepp (FRG)       N

      Shirt Number           Player Name Position Event  Goals  Match Year
1390             0          Rudolf RAFTL       GK   NaN    NaN        1938
1392             0     Willibald SCHMAUS      NaN   NaN    NaN        1938
1394             0         Josef GAUCHEL      NaN  G29'    1.0        1938
1396             0       Rudolf GELLESCH      NaN   NaN    NaN        1938
1398             0            Paul JANES      NaN   NaN    NaN        1938
1400             0       Albin KITZINGER      NaN   NaN    NaN        1938
1402             0        Andreas KUPFER      NaN   NaN    NaN        1938
1404             0         Ernest LEHNER      NaN   NaN    NaN        1938
1406             0             Hans MOCK        C   NaN    NaN        1938
1408             0           Hans PESSER      NaN  R96'    NaN        1938
1410             0    Willhelm HAHNEMANN      NaN   NaN    NaN        1938
1412             0         Fritz BUCHLOH      NaN   NaN    NaN        1938
1414             0  Reinhold MUENZENBERG      NaN   NaN    NaN        1938
1416             0        Leopold NEUMER      NaN   NaN    NaN        1938
1418             0    Ludwig GOLDBRUNNER      NaN   NaN    NaN        1938
1420             0            Hans JAKOB      NaN   NaN    NaN        1938
1422             0         Otto SIFFLING      NaN   NaN    NaN        1938
1424             0        Stefan SKOUMAL      NaN   NaN    NaN        1938
1426             0        Jakob STREITLE      NaN   NaN    NaN        1938
1428             0           Josef STROH      NaN   NaN    NaN        1938
1430             0          Fritz SZEPAN      NaN   NaN    NaN        1938
1432             0          Franz WAGNER      NaN   NaN    NaN        1938
1719             0          Rudolf RAFTL       GK   NaN    NaN        1938
1721             0    Willhelm HAHNEMANN      NaN   G8'    1.0        1938
1723             0        Stefan SKOUMAL      NaN   NaN    NaN        1938
1725             0        Jakob STREITLE      NaN   NaN    NaN        1938
1727             0           Josef STROH      NaN   NaN    NaN        1938
1729             0          Fritz SZEPAN        C   NaN    NaN        1938
1731             0    Ludwig GOLDBRUNNER      NaN   NaN    NaN        1938
1733             0        Andreas KUPFER      NaN   NaN    NaN        1938
1735             0         Ernest LEHNER      NaN   NaN    NaN        1938
1737             0            Paul JANES      NaN   NaN    NaN        1938
1739             0        Leopold NEUMER      NaN   NaN    NaN        1938
1741             0           Hans PESSER      NaN   NaN    NaN        1938
1743             0       Albin KITZINGER      NaN   NaN    NaN        1938
1745             0             Hans MOCK      NaN   NaN    NaN        1938
1747             0  Reinhold MUENZENBERG      NaN   NaN    NaN        1938
1749             0            Hans JAKOB      NaN   NaN    NaN        1938
1751             0         Fritz BUCHLOH      NaN   NaN    NaN        1938
1753             0         Josef GAUCHEL      NaN   NaN    NaN        1938
1755             0       Rudolf GELLESCH      NaN   NaN    NaN        1938
1757             0          Franz WAGNER      NaN   NaN    NaN        1938
1759             0     Willibald SCHMAUS      NaN   NaN    NaN        1938
1761             0         Otto SIFFLING      NaN   NaN    NaN        1938
Empty DataFrame
Columns: [RoundID, MatchID, Team Initials, Coach Name, Line-up, Shirt Number, Player Name, Position, Event, Goals, Match Year]
Index: []
      RoundID  MatchID Team Initials            Coach Name Line-up
3245      211     1283           GER  HERBERGER Sepp (FRG)       S  \
3247      211     1283           GER  HERBERGER Sepp (FRG)       S
3249      211     1283           GER  HERBERGER Sepp (FRG)       S
3251      211     1283           GER  HERBERGER Sepp (FRG)       S
3253      211     1283           GER  HERBERGER Sepp (FRG)       S
...       ...      ...           ...                   ...     ...
4199     3484     1278           GER  HERBERGER Sepp (FRG)       N
4201     3484     1278           GER  HERBERGER Sepp (FRG)       N
4203     3484     1278           GER  HERBERGER Sepp (FRG)       N
4205     3484     1278           GER  HERBERGER Sepp (FRG)       N
4207     3484     1278           GER  HERBERGER Sepp (FRG)       N

      Shirt Number        Player Name Position Event  Goals  Match Year
3245             1         Toni TUREK       GK   NaN    NaN        1954
3247             2       Fritz LABAND      NaN   NaN    NaN        1954
3249             3   Werner KOHLMEYER      NaN   NaN    NaN        1954
3251             6        Horst ECKEL      NaN   NaN    NaN        1954
3253             7       Jupp POSIPAL      NaN   NaN    NaN        1954
...            ...                ...      ...   ...    ...         ...
4199            17   Richard HERRMANN      NaN   NaN    NaN        1954
4201            18      Uli BIESINGER      NaN   NaN    NaN        1954
4203            19       Alfred PFAFF      NaN   NaN    NaN        1954
4205            21       Heinz KUBSCH      NaN   NaN    NaN        1954
4207            22  Heinz KWIATKOWSKI      NaN   NaN    NaN        1954

[132 rows x 11 columns]
      RoundID  MatchID Team Initials            Coach Name Line-up
4298      220     1323           GER  HERBERGER Sepp (FRG)       S  \
4300      220     1323           GER  HERBERGER Sepp (FRG)       S
4302      220     1323           GER  HERBERGER Sepp (FRG)       S
4304      220     1323           GER  HERBERGER Sepp (FRG)       S
4306      220     1323           GER  HERBERGER Sepp (FRG)       S
...       ...      ...           ...                   ...     ...
5696     3483     1382           GER  HERBERGER Sepp (FRG)       N
5698     3483     1382           GER  HERBERGER Sepp (FRG)       N
5700     3483     1382           GER  HERBERGER Sepp (FRG)       N
5702     3483     1382           GER  HERBERGER Sepp (FRG)       N
5704     3483     1382           GER  HERBERGER Sepp (FRG)       N

      Shirt Number       Player Name Position Event  Goals  Match Year
4298             1  Fritz HERKENRATH       GK   NaN    NaN        1958
4300             2   Herbert ERHARDT      NaN   NaN    NaN        1958
4302             3   Erich JUSKOWIAK      NaN   NaN    NaN        1958
4304             4       Horst ECKEL      NaN   NaN    NaN        1958
4306             6   Horst SZYMANIAK      NaN   NaN    NaN        1958
...            ...               ...      ...   ...    ...         ...
5696            13       Berni KLODT      NaN   NaN    NaN        1958
5698            18     Rudi HOFFMANN      NaN   NaN    NaN        1958
5700            19   Wolfgang PETERS      NaN   NaN    NaN        1958
5702            20     Hermann NUBER      NaN   NaN    NaN        1958
5704            21   Gunter SAWITZKI      NaN   NaN    NaN        1958

[132 rows x 11 columns]
      RoundID  MatchID Team Initials            Coach Name Line-up
6057      231     1507           GER  HERBERGER Sepp (FRG)       S  \
6059      231     1507           GER  HERBERGER Sepp (FRG)       S
6061      231     1507           GER  HERBERGER Sepp (FRG)       S
6063      231     1507           GER  HERBERGER Sepp (FRG)       S
6065      231     1507           GER  HERBERGER Sepp (FRG)       S
...       ...      ...           ...                   ...     ...
6972      232     1511           GER  HERBERGER Sepp (FRG)       N
6974      232     1511           GER  HERBERGER Sepp (FRG)       N
6976      232     1511           GER  HERBERGER Sepp (FRG)       N
6978      232     1511           GER  HERBERGER Sepp (FRG)       N
6980      232     1511           GER  HERBERGER Sepp (FRG)       N

      Shirt Number              Player Name Position Event  Goals  Match Year
6057            22         Wolfgang FAHRIAN       GK   NaN    NaN        1962
6059             2          Herbert ERHARDT      NaN   NaN    NaN        1962
6061             3  Karl-Heinz SCHNELLINGER      NaN   NaN    NaN        1962
6063             4             Willi SCHULZ      NaN   NaN    NaN        1962
6065             6          Horst SZYMANIAK      NaN   NaN    NaN        1962
...            ...                      ...      ...   ...    ...         ...
6972            17          Engelbert KRAUS      NaN   NaN    NaN        1962
6974            18          Guenter HERMANN      NaN   NaN    NaN        1962
6976            19             Heinz STREHL      NaN   NaN    NaN        1962
6978            20            Heinz VOLLMAR      NaN   NaN    NaN        1962
6980            21          Gunter SAWITZKI      NaN   NaN    NaN        1962

[88 rows x 11 columns]
      RoundID  MatchID Team Initials           Coach Name Line-up
7201      238     1656           GER  SCHOEN Helmut (FRG)       S  \
7203      238     1656           GER  SCHOEN Helmut (FRG)       S
7205      238     1656           GER  SCHOEN Helmut (FRG)       S
7207      238     1656           GER  SCHOEN Helmut (FRG)       S
7209      238     1656           GER  SCHOEN Helmut (FRG)       S
...       ...      ...           ...                  ...     ...
8556     3478     1633           GER  SCHOEN Helmut (FRG)       N
8558     3478     1633           GER  SCHOEN Helmut (FRG)       N
8560     3478     1633           GER  SCHOEN Helmut (FRG)       N
8562     3478     1633           GER  SCHOEN Helmut (FRG)       N
8564     3478     1633           GER  SCHOEN Helmut (FRG)       N

      Shirt Number              Player Name Position      Event  Goals
7201             1           Hans TILKOWSKI       GK        NaN    NaN  \
7203             2    Horst-Dieter HOETTGES      NaN        NaN    NaN
7205             3  Karl-Heinz SCHNELLINGER      NaN        NaN    NaN
7207             4        Franz BECKENBAUER      NaN  G39' G52'    2.0
7209             5             Willi SCHULZ      NaN        NaN    NaN
...            ...                      ...      ...        ...    ...
8556            18     Klaus-Dieter SIELOFF      NaN        NaN    NaN
8558            19           Werner KRAEMER      NaN        NaN    NaN
8560            20        Juergen GRABOWSKI      NaN        NaN    NaN
8562            21          Guenter BERNARD      NaN        NaN    NaN
8564            22               Sepp MAIER      NaN        NaN    NaN

      Match Year
7201        1966
7203        1966
7205        1966
7207        1966
7209        1966
...          ...
8556        1966
8558        1966
8560        1966
8562        1966
8564        1966

[132 rows x 11 columns]
      RoundID  MatchID Team Initials           Coach Name Line-up
8785      250     1839           GER  SCHOEN Helmut (FRG)       S  \
8787      250     1839           GER  SCHOEN Helmut (FRG)       S
8789      250     1839           GER  SCHOEN Helmut (FRG)       S
8791      250     1839           GER  SCHOEN Helmut (FRG)       S
8793      250     1839           GER  SCHOEN Helmut (FRG)       S
...       ...      ...           ...                  ...     ...
9910     3477     1843           GER  SCHOEN Helmut (FRG)       N
9912     3477     1843           GER  SCHOEN Helmut (FRG)       N
9914     3477     1843           GER  SCHOEN Helmut (FRG)       N
9916     3477     1843           GER  SCHOEN Helmut (FRG)       N
9918     3477     1843           GER  SCHOEN Helmut (FRG)       N

      Shirt Number            Player Name Position      Event  Goals
8785             1             Sepp MAIER       GK        NaN    NaN  \
8787             2  Horst-Dieter HOETTGES      NaN       O77'    NaN
8789             4      Franz BECKENBAUER      NaN        NaN    NaN
8791             5           Willi SCHULZ      NaN        NaN    NaN
8793             7            Berti VOGTS      NaN        NaN    NaN
...            ...                    ...      ...        ...    ...
9910            16             Max LORENZ      NaN  Y1' IH46'    NaN
9912            17           Hennes LOEHR      NaN   Y1' I73'    NaN
9914            18   Klaus-Dieter SIELOFF      NaN        NaN    NaN
9916            19         Peter DIETRICH      NaN        NaN    NaN
9918            20      Juergen GRABOWSKI      NaN        NaN    NaN

      Match Year
8785        1970
8787        1970
8789        1970
8791        1970
8793        1970
...          ...
9910        1970
9912        1970
9914        1970
9916        1970
9918        1970

[132 rows x 11 columns]
       RoundID  MatchID Team Initials           Coach Name Line-up
10008      262     2003           GER  SCHOEN Helmut (FRG)       S  \
10010      262     2003           GER  SCHOEN Helmut (FRG)       S
10012      262     2003           GER  SCHOEN Helmut (FRG)       S
10014      262     2003           GER  SCHOEN Helmut (FRG)       S
10016      262     2003           GER  SCHOEN Helmut (FRG)       S
...        ...      ...           ...                  ...     ...
11627      605     2063           GER  SCHOEN Helmut (FRG)       N
11629      605     2063           GER  SCHOEN Helmut (FRG)       N
11631      605     2063           GER  SCHOEN Helmut (FRG)       N
11633      605     2063           GER  SCHOEN Helmut (FRG)       N
11635      605     2063           GER  SCHOEN Helmut (FRG)       N

       Shirt Number               Player Name Position Event  Goals
10008             1                Sepp MAIER       GK   NaN    NaN  \
10010             2               Berti VOGTS      NaN   NaN    NaN
10012             3             Paul BREITNER      NaN  G18'    1.0
10014             4  Hans Georg SCHWARZENBECK      NaN   NaN    NaN
10016             5         Franz BECKENBAUER        C   NaN    NaN
...             ...                       ...      ...   ...    ...
11627            18             Dieter HERZOG      NaN   NaN    NaN
11629            19          Jupp KAPPELLMANN      NaN   NaN    NaN
11631            20            Helmut KREMERS      NaN   NaN    NaN
11633            21            Norbert NIGBUR      NaN   NaN    NaN
11635            22            Wolfgang KLEFF      NaN   NaN    NaN

       Match Year
10008        1974
10010        1974
10012        1974
10014        1974
10016        1974
...           ...
11627        1974
11629        1974
11631        1974
11633        1974
11635        1974

[154 rows x 11 columns]
       RoundID  MatchID Team Initials           Coach Name Line-up
11636      278     2351           GER  SCHOEN Helmut (FRG)       S  \
11638      278     2351           GER  SCHOEN Helmut (FRG)       S
11640      278     2351           GER  SCHOEN Helmut (FRG)       S
11642      278     2351           GER  SCHOEN Helmut (FRG)       S
11644      278     2351           GER  SCHOEN Helmut (FRG)       S
...        ...      ...           ...                  ...     ...
13123      279     2217           GER  SCHOEN Helmut (FRG)       N
13125      279     2217           GER  SCHOEN Helmut (FRG)       N
13127      279     2217           GER  SCHOEN Helmut (FRG)       N
13129      279     2217           GER  SCHOEN Helmut (FRG)       N
13131      279     2217           GER  SCHOEN Helmut (FRG)       N


580           None
581    (GER, 1934)
582    (GER, 1938)
583           None
584    (GER, 1954)
585    (GER, 1958)
586    (GER, 1962)
587    (GER, 1966)
588    (GER, 1970)
589    (GER, 1974)
590    (GER, 1978)
591    (GER, 1982)
592    (GER, 1986)
593    (GER, 1990)
594    (GER, 1994)
595    (GER, 1998)
596    (GER, 2002)
597    (GER, 2006)
598    (GER, 2010)
599    (GER, 2014)
dtype: object

In [392]:
test = df_players[df_players['Event'].str.count('G') > 0]

In [512]:
zzz = []
for k in df_players['Event']:
    if pd.notna(k):
        zzz += (re.sub(r'[^a-zA-Z\s]', '', k).split())
all_events = list(set(zzz))

In [513]:
all_events

['O', 'I', 'IH', 'W', 'MP', 'G', 'Y', 'RSY', 'P', 'R', 'OH']

In [519]:
df_players[df_players['Event'].str.count('R')>0]

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goals,Match Year
113,201,1098,PER,BRU Francisco (ESP),S,0,Placido GALINDO,C,R70',NaN,1930
1146,418,1106,HUN,NADAS Odon (HUN),S,0,Imre MARKOS,NaN,R63',NaN,1934
1408,206,1165,GER,HERBERGER Sepp (FRG),S,0,Hans PESSER,NaN,R96',NaN,1938
1766,429,1152,BRA,PIMENTA Ademar (BRA),S,0,MACHADO,NaN,R89',NaN,1938
1770,429,1152,BRA,PIMENTA Ademar (BRA),S,0,ZEZE PROCOPIO,NaN,R14',NaN,1938
...,...,...,...,...,...,...,...,...,...,...,...
35768,255931,300186465,ITA,Cesare PRANDELLI (ITA),S,8,MARCHISIO,NaN,R59',NaN,2014
36102,255931,300186515,ECU,RUEDA Reinaldo (COL),S,16,A. VALENCIA,C,R50',NaN,2014
36233,255931,300186480,BEL,WILMOTS Marc (BEL),S,16,DEFOUR,NaN,R45',NaN,2014
36918,255951,300186459,CRC,PINTO Jorge Luis (COL),S,6,DUARTE O.,NaN,Y42' Y66' RSY66',NaN,2014
37194,255951,300186459,CRC,PINTO Jorge Luis (COL),S,6,DUARTE O.,NaN,Y42' Y66' RSY66',NaN,2014